name: branch_protection
description: Default branch protection policy
resource: repository
where: 
configuration:
  branchProtectionRules:
  - branchNamePattern: policy_test
    requiredApprovingReviewsCount: 1
    # dismissStaleReviews: true
    # restrictsReviewDismissals: true
    # whoCanDismissReviews:
    # # A username
    # - petyan
    # # A team name
    # - startrightdevs
    requiresStrictStatusChecks: true
    requiredStatusChecks:
    - license/cla
    isAdminEnforced: false
    restrictsPushes: true
    whoCanPush:
    # A username
    - likamrat
    # A team name
    # - startrightdevs
    allowsForcePushes: true
    allowsDeletions: true