name: CSpell
on:
  push:
    branches:
      - main # Modify if you use a different main branch name, such as the legacy "master" name.
  pull_request:
    branches:
      - main # Modify if you use a different main branch name, such as the legacy "master" name.

jobs:
  spellchecking:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Check out the code
      - uses: actions/setup-node@v4
        name: Setup Node.js
        with:
          node-version: "20"
      - name: Install cspell
        run: npm install -g cspell
      - name: Run cspell check
        run: cspell --config ./cSpell.json "**/*.md"
        continue-on-error: true
