name: Spell Check

on:
  pull_request:
    paths:
      - '**/*.md'
      - '**/*.bicep'
      - '**/*.tf'
      - '**/*.tfvars'
      - '**/*.json'
      - '**/*.yml'
      - '**/*.yaml'
      - '**/*.py'
      - '**/*.sh'
      - '**/*.ps1'

jobs:
  cspell-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install cspell
      run: npm install -g cspell

    - name: Run cspell
      id: spellcheck
      run: |
        npx cspell --config .cspell.json . > result.txt || true
        cat result.txt
        echo "result<<EOF" >> $GITHUB_OUTPUT
        cat result.txt >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

    - name: Comment on PR if spelling issues found
      if: steps.spellcheck.outputs.result != ''
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        path: result.txt
