name: Lint

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # Updated to v4
      - name: Set up Node.js
        uses: actions/setup-node@v4 # Updated to v4
        with:
          node-version: '20' # Updated to a current LTS version (e.g., 18, 20)
          cache: 'npm' # Added npm caching

      - name: List files in checkout directory # Diagnostic step
        run: ls -la

      - name: Install dependencies
        run: npm install
      - name: Run ESLint
        run: npm run lint

      - name: Post comment on PR if linting fails
        if: failure() # This condition correctly triggers on previous step failure
        uses: actions/github-script@v7 # Updated to v7
        with:
          script: |
            const prNumber = context.issue.number;
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const body = `🚨 **Linting Issues Found** 🚨\n\nESLint has detected issues in this PR. Please review the workflow logs for details and address the reported problems.`;

            github.rest.issues.createComment({
              issue_number: prNumber,
              owner: owner,
              repo: repo,
              body: body
            });
