name: Spell Check with PR Annotations

on:
  pull_request:
    branches:
      - main
      - integration
    paths:
      - '**/*.{md,txt,ps1,sh,py,js,ts,json,yml,yaml}'  # Check all relevant files
      - 'cspell/**'  # Also check the cspell config files
  push:
    branches:
      - main
      - integration
    paths:
      - '**/*.{md,txt,ps1,sh,py,js,ts,json,yml,yaml}'
      - 'cspell/**'

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install cspell
        run: npm install -g cspell

      - name: Run cspell with annotations
        uses: streetsidesoftware/cspell-action@v6
        with:
          config: './cspell/cspell.json'  # Use the config in the cspell folder
          inline: 'error'  # Valid values are 'error', 'warning', or 'none'
          strict: true  # Fail the build on errors
