name: Spell Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  spellcheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install CSpell
        run: npm install -g cspell

      - name: Debug file list
        run: |
          echo "Files in repo:"
          find . -type f

      - name: Run Spell Check
        run: |
          cspell "**/*" \
            --config ./cspell/cspell.json \
            --no-progress \
            --show-context \
            --color

      - name: Run CSpell with Reviewdog (PR feedback)
        uses: reviewdog/action-setup@e04ffabe3898a0af8d0fb1af00c188831c4b5893 # v1.3.2
        with:
          reviewdog_version: latest # Optional. [latest,nightly,v.X.Y.Z]
        # cspell_args: "--config ./cspell/cspell.json --no-progress --show-context --color '**/*'"
