name: Spell Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  spellcheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install CSpell
        run: npm install -g cspell

      - name: Debug file list
        run: |
          echo "Files in repo:"
          find . -type f

      - name: Run Spell Check
        run: |
          cspell "**/*" \
            --config ./cspell/cspell.json \
            --no-progress \
            --show-context \
            --color

      - name: Run CSpell with Reviewdog (PR feedback)
        uses: reviewdog/action-cspell@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          cspell_args: "--config ./cspell/cspell.json --no-progress --show-context --color '**/*'"
