name: Vale PR Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  vale:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Vale
        run: |
          curl -fsSL https://github.com/errata-ai/vale/releases/latest/download/vale_Linux_64-bit.tar.gz | tar -xz
          sudo mv vale /usr/local/bin

      - name: Run Vale
        run: |
          mkdir -p .vale
          echo 'StylesPath = .github/styles' > .vale/.vale.ini
          echo 'MinAlertLevel = suggestion' >> .vale/.vale.ini
          echo '[*.md]' >> .vale/.vale.ini
          echo 'BasedOnStyles = Vale' >> .vale/.vale.ini
          vale --config=.vale/.vale.ini . > vale-output.txt || true

      - name: Format Vale output for PR comment
        run: |
          echo '### :mag_right: Vale Linting Report' > vale-comment.txt
          echo '' >> vale-comment.txt
          if [ -s vale-output.txt ]; then
            cat vale-output.txt >> vale-comment.txt
          else
            echo "✅ No linting issues found." >> vale-comment.txt
          fi

      - name: Generate GitHub App token
        id: app-token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.JUMPSTART_ACCESS_APP_ID }}
          private_key: ${{ secrets.JUMPSTART_ACCESS_APP_PRIVATE_KEY }}

      - name: Comment on PR with Vale results
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
          issue-number: ${{ github.event.pull_request.number }}
          body-path: vale-comment.txt
